pub const MessageType = enum(u8) {
    registration_result = 1,
    realtime_update = 2,
    realtime_car_update = 3,
    entry_list = 4,
    track_data = 5,
    entry_list_car = 6,
    broadcasting_event = 7,
};

pub const DriverCategory = enum(u8) {
    bronze = 0,
    silver = 1,
    gold = 2,
    platinum = 3,
    unknown = 255,
};

pub const CarLocation = enum(u8) {
    unknown = 0,
    track = 1,
    pitlane = 2,
    pit_entry = 3,
    pit_exit = 4,
};

pub const SessionPhase = enum(u8) {
    unknown = 0,
    starting = 1,
    pre_formation = 2,
    formation = 3,
    pre_session = 4,
    session = 5,
    session_end = 6,
    post_session = 7,
    result = 8,
};

pub const SessionType = enum(u8) {
    practice = 0,
    qualifying = 4,
    superpole = 9,
    race = 10,
    hotlap = 11,
    hotstint = 12,
    hotlap_superpole = 13,
    replay = 14,
};

pub const CameraSetName = enum {
    Driveable,
    Onboard,
    Helicam,
    Pitlane,
    Set1,
    Set2,
    SetVR,
};

pub const CameraSets = struct {
    pub const Driveable = enum { Chase, FarChase, Bonnet, DashPro, Cockpit, Dash, Helmet };
    pub const Onboard = enum { Onboard0, Onboard1, Onboard2, Onboard3 };
    pub const Helicam = enum { Helicam };
    pub const Pitlane = enum { CameraPit1 };
    pub const Set1 = enum {
        CameraTV1,
        CameraTV1B_5,
        CameraTV2,
        CameraTV4,
        CameraTV4B,
        CameraTV5,
        CameraTV6_0,
        CameraTV7_0,
        CameraTV8,
        CameraTV9,
        CameraTV10_16,
        CameraTV11,
        CameraTV12_5,
        CameraTV13,
        CameraTV14,
        CameraTV15,
        CameraTV16_1,
    };
    pub const Set2 = enum {
        CameraTV17,
        CameraTV18,
        CameraTV19,
        CameraTV20,
        CameraTV21,
        CameraTV22,
        CameraTV23,
        CameraTV24,
        CameraTV25,
        CameraTV26,
        CameraTV27,
    };
    pub const SetVR = enum {
        CameraVR1,
        CameraVR2,
        CameraVR3,
        CameraVR4,
        CameraVR5,
        CameraVR6,
        CameraVR7,
        CameraVR8,
    };
};

pub const HudPage = enum {
    Blank,
    @"Basic HUD",
    Help,
    TimeTable,
    Broadcasting,
    TrackMap,
};

pub const BroadcastingCarEventType = enum(u8) {
    none = 0,
    green_flag = 1,
    session_over = 2,
    penalty_comm_msg = 3,
    accident = 4,
    lap_completed = 5,
    best_session_lap = 6,
    best_personal_lap = 7,
};

pub const Nationality = enum(u16) {
    any = 0,
    italy = 1,
    germany = 2,
    france = 3,
    spain = 4,
    great_britain = 5,
    hungary = 6,
    belgium = 7,
    switzerland = 8,
    austria = 9,
    russia = 10,
    thailand = 11,
    netherlands = 12,
    poland = 13,
    argentina = 14,
    monaco = 15,
    ireland = 16,
    brazil = 17,
    south_africa = 18,
    puerto_rico = 19,
    slovakia = 20,
    oman = 21,
    greece = 22,
    saudi_arabia = 23,
    norway = 24,
    turkey = 25,
    south_korea = 26,
    lebanon = 27,
    armenia = 28,
    mexico = 29,
    sweden = 30,
    finland = 31,
    denmark = 32,
    croatia = 33,
    canada = 34,
    china = 35,
    portugal = 36,
    singapore = 37,
    indonesia = 38,
    usa = 39,
    new_zealand = 40,
    australia = 41,
    san_marino = 42,
    uae = 43,
    luxembourg = 44,
    kuwait = 45,
    hong_kong = 46,
    colombia = 47,
    japan = 48,
    andorra = 49,
    azerbaijan = 50,
    bulgaria = 51,
    cuba = 52,
    czech_re = 53,
    estonia = 54,
    georgia = 55,
    india = 56,
    israel = 57,
    jamaica = 58,
    latvia = 59,
    lithuania = 60,
    macau = 61,
    malaysia = 62,
    nepal = 63,
    new_caledonia = 64,
    nigeria = 65,
    northern_ireland = 66,
    papua_new_guinea = 67,
    philippines = 68,
    qatar = 69,
    romania = 70,
    scotland = 71,
    serbia = 72,
    slovenia = 73,
    taiwan = 74,
    ukraine = 75,
    venezuela = 76,
    wales = 77,
    iran = 78,
    bahrain = 79,
    zimbabwe = 80,
    chinese_taipei = 81,
    chile = 82,
    uruguay = 83,
    madagascar = 84,
};
